# Конфигурация системы расписания СЗГМУ
# Configuration for SZGMU schedule system

# Расписание звонков (время занятий)
schedule_rings:
  # Семинары (сдвоенные пары)
  seminars:
    - pair_number: [1, 2]
      time_slots:
        - start: "09:00"
          end: "10:30"
        - start: "10:45" 
          end: "12:15"
    - pair_number: [3, 4]
      time_slots:
        - start: "13:10"
          end: "14:40"
        - start: "14:55"
          end: "16:25"

  # Лекции (одинарные пары)
  lectures:
    - pair_number: 1
      time_slots:
        - start: "09:00"
          end: "09:45"
        - start: "09:50"
          end: "10:35"
    - pair_number: 2
      time_slots:
        - start: "10:55"
          end: "11:40"
        - start: "11:45"
          end: "12:30"
    - pair_number: 3
      time_slots:
        - start: "13:10"
          end: "13:55"
        - start: "14:00"
          end: "14:45"
    - pair_number: 4
      time_slots:
        - start: "15:00"
          end: "15:45"
        - start: "15:50"
          end: "16:35"
    - pair_number: 5
      time_slots:
        - start: "16:45"
          end: "17:30"
        - start: "17:35"
          end: "18:20"

# Дни недели
week_days:
  пн: 0
  вт: 1
  ср: 2
  чт: 3
  пт: 4
  сб: 5
  вс: 6

week_days_inverted:
  0: "Пн"
  1: "Вт" 
  2: "Ср"
  3: "Чт"
  4: "Пт"
  5: "Сб"
  6: "Вс"

# Настройки Excel файлов
excel:
  column_widths: [8, 13, 4, 4, 16, 4, 20]
  default_font_size: 11
  header_font_size: 12

# Настройки по умолчанию
defaults:
  swimming_pool_name: "ФП"  # Физическая подготовка
  add_breaks: false
  add_mark: true

# API настройки
api:
  base_url: "https://frsview.szgmu.ru/api"
  timeout: 30
  endpoints:
    find_schedules: "/xlsxSchedule/findAll/0"
    get_schedule: "/xlsxSchedule/findById"
    get_filters: "/xlsxSchedule/getFilters"

# Настройки бота
bot:
  default_language: "ru"
  max_search_results: 10
  file_cache_ttl: 900  # 15 минут
  
  # Эмодзи для интерфейса
  emojis:
    loading: "⏳"
    success: "✅"
    error: "❌"
    info: "ℹ️"
    warning: "⚠️"
    schedule: "📅"
    homework: "📝"
    grades: "🎯"
    absences: "❌"
    profile: "👤"
    settings: "⚙️"
    search: "🔍"
    back: "⬅️"
    home: "🏠"
    excel: "📊"
    calendar: "📅"
    document: "📎"

  # Тексты интерфейса
  messages:
    welcome: "👋 Привет! Я твой учебный помощник."
    profile_setup_needed: "Для начала работы нужно выбрать твою группу:"
    loading_filters: "⏳ Загружаю доступные параметры..."
    no_results: "❌ Ничего не найдено. Попробуйте изменить параметры."
    file_generated: "✅ Файл успешно отправлен! Хотите начать новый поиск?"
    error_generation: "❌ Ошибка при генерации файла"

# Система заявлений СЗГМУ
applications:
  # Правила: для каждой дисциплины + 1 объяснительная в дирекцию
  document_types:
    discipline_application:
      name: "Заявление по дисциплине" 
      description: "Отдельное заявление для каждой дисциплины"
      recipients: "На кафедру/преподавателю"
      template: "templates/discipline_application.docx"
    explanatory_note:
      name: "Объяснительная записка"
      description: "Одна объяснительная в дирекцию института на все пропуски одной серии"
      recipients: "Дирекция института"
      template: "templates/explanatory_note.docx"
  
  # Стандартные причины пропусков (из практики СЗГМУ)
  absence_reasons:
    illness:
      name: "По болезни"
      emoji: "🤒"
      requires_medical_docs: true
    family_circumstances:
      name: "Семейные обстоятельства"
      emoji: "🚗"
      requires_medical_docs: false
    medical_examination:
      name: "Медицинский осмотр" 
      emoji: "🏥"
      requires_medical_docs: false
    official_business:
      name: "По вызову официальных органов"
      emoji: "🏛️"
      requires_medical_docs: false

# Академические настройки
academic:
  # Семестры
  semesters:
    autumn:
      name: "осенний"
      start_month: 9
      months: [9, 10, 11, 12, 1]
    spring:
      name: "весенний" 
      start_month: 2
      months: [2, 3, 4, 5, 6]
  
  # Типы занятий
  lesson_types:
    lecture:
      code: "л"
      api_name: "лекционного"
      name: "Лекция"
      emoji: "📖"
    seminar:
      code: "с"  
      api_name: "семинарского"
      name: "Семинар"
      emoji: "💬"
  
  # Типы оценок
  grade_types:
    - code: "exam"
      name: "Экзамен"
      emoji: "📋"
    - code: "test"
      name: "Зачет"
      emoji: "📊"  
    - code: "control"
      name: "Контрольная"
      emoji: "📝"
    - code: "lab"
      name: "Лабораторная"
      emoji: "🧪"
    - code: "oral"
      name: "Устный ответ"
      emoji: "📖"
    - code: "essay"
      name: "Реферат"
      emoji: "📄"

# Система напоминаний
reminders:
  # Типы напоминаний
  types:
    - type: "before_class"
      name: "Перед занятием"
      default_minutes: 30
    - type: "homework_deadline"
      name: "Дедлайн ДЗ"
      default_hours: 24
    - type: "grade_entry"
      name: "Внесение оценки"
      default_enabled: true
    - type: "absence_makeup"
      name: "Отработка пропуска"
      default_days: 7
  
  # Время отправки
  default_times:
    morning: "08:00"
    evening: "20:00"
    before_class: 30  # минут до занятия

# Академические параметры СЗГМУ (на основе ответов пользователя)
academic_szgmu:
  directions:
    # Направления подготовки
    ld: "Лечебное дело"
    mpd: "Медико-профилактическое дело"  
    # Остальные направления требуют уточнения
  
  schedule_info:
    # Расписание экзаменов
    exam_schedule_url: "https://szgmu.ru/rus/m/660/"
    exam_updates_priority: true  # "когда что то меняется оно в первую очередь появляется там"
    exam_pdf_structure: false   # "вероятно нет"
    exam_other_formats: false   # "нет"
  
  academic_calendar:
    semester_start: "Как прикажет ректор"
    faculty_exceptions: false   # "нет"
    holidays_handling: "Не ставят занятия в расписание"
  
  teachers:
    group_assignment: true      # "для групп обычно закрепляется преподаватель"
    teacher_type: "ведущий преподаватель"  # не куратор
    schedule_display_needed: true  # "было бы неплохо указывать препода в расписании"
  
  study_plans:
    location: "SDO Moodle (sdo.szgmu.ru)"
    access: "По логину и паролю студента"
    individualized: true        # "всё слишком индивидуально"
    student_upload: true        # "студент может подгружать темы самостоятельно"
  
  knl_kns_system:
    # Анализ документов показал связь с промежуточной аттестацией
    needs_document_analysis: true
    affects_attestation: true   # "связана ли с количеством пропусков? да"
    bot_integration: "optional" # "опционально"
    # Предположительно:
    knl_abbreviation: "Контроль на лекциях (?)"  # требует подтверждения
    kns_abbreviation: "Контроль на семинарах (?)"  # требует подтверждения
    related_to_average_score: true  # упоминается "общий средний балл" в приказе
    makeup_deadline: 30  # "в течение месяца" для отработок
  
  document_workflow:
    # Куда подавать документы
    discipline_application_recipient: "На кафедру или преподавателю"
    explanatory_note_recipient: "Дирекция института" 
    document_format: "Печатный, с подписью студента"
    delivery_method: "Лично в дирекцию"
  
  subgroups_vs_groups:
    # Подгруппы используются для разделения на занятия
    seminar_schedule_level: "group"  # семинары одинаковы для всей группы
    subgroup_usage: "Только для разделения на занятия, поле избыточное"
    api_field_redundant: true
  
  makeup_classes:
    # Система отработок индивидуальная
    individual_approach: true
    depends_on_teacher: true
    depends_on_department: true
    note: "Всё индивидуально. Зависит от препода и кафедры"
  
  # Новые правила промежуточной аттестации (Приказ № 408-О от 28.02.2025)
  intermediate_attestation_2025:
    effective_date: "2025-03-17"
    applies_to_semester: "весенний 2024/2025"
    
    # Особенности весеннего семестра 2024/2025
    spring_semester_2024_2025:
      test_deadline: "до последнего дня семестра"
      assessment_materials: "из рабочих программ дисциплин"
      average_score_consideration: true
      department_discretion: "порядок определяют кафедры самостоятельно"
      
    # Отложенные до осеннего семестра 2025/2026 пункты
    deferred_until_autumn_2025:
      paragraphs: ["1.6", "3.2", "3.3", "3.3.1-3.3.2", "4.2", "4.2.1-4.2.5", "4.3", "4.3.1-4.3.3"]
      
    # Действующие старые документы до осени 2025
    active_legacy_documents:
      - name: "Положение о балльно-рейтинговой системе"
        order: "№ 1709-О от 31.08.2022"
        applies_to: "только осенний семестр 2024/2025"
      - name: "Положение о текущем контроле и промежуточной аттестации"
        order: "№ 1723-О от 31.08.2022" 
        sections: "разделы 1, 3-5"
        note: "КНЛ/КНС может содержаться здесь"
      - name: "Порядок проведения экзаменов"
        order: "№ 1719-О от 31.08.2022"
        
    # Обязанности кафедр
    department_obligations:
      program_updates_deadline: "2025-04-30"
      new_materials_effective: "осенний семестр 2025-2026"
      test_procedure_approval: "на заседании кафедры"
      student_notification: "через ЭИОС Университета"
      staff_familiarization: "под личную подпись"

# Файлы и пути
paths:
  templates: "templates/"
  output: "output/"
  logs: "logs/"
  cache: "cache/"
  temp: "files/temp/"