[mypy]
python_version = 3.9
warn_return_any = True
warn_unused_configs = True
disallow_untyped_defs = True
ignore_missing_imports = True

# Исправляем конфликт модулей
mypy_path = app

[mypy-app.*]
ignore_errors = False

[mypy-services.*]
ignore_errors = False
